name: waari_water
description: A new Flutter project.

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  dio: ^5.3.2
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.9
  flutter_launcher_icons: ^0.13.1
  flutter_screenutil: null
  flutter_svg: ^2.0.9
  fluttertoast: ^8.2.4
  get_it: ^7.6.4
  injectable: ^2.3.2
  mqtt_client: ^10.0.1
  pinput: ^3.0.1
  shared_preferences: ^2.2.2
dev_dependencies:
  build_runner: ^2.4.7
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  injectable_generator: ^2.4.1
  mocktail: ^1.0.1
